spring:
  datasource:
    url: jdbc:mysql://localhost:3306/practice?characterEncoding=utf8&autoReconnect=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: liaoyangzhou